version: '2'

services:
   db:
     image: mysql:5.7
     volumes:
       - wp_pusher_db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
     ports:
        - "3306:3306"
   wordpress:
     depends_on:
       - db
     image: tatemz/wp-cli
     volumes:
       - ../src/wp-content/plugins/:/var/www/html/wp-content/plugins/
       - ../src/wp-content/themes/:/var/www/html/wp-content/themes/
       - ../scripts/:/var/www/html/scripts
     ports:
       - "80:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_PASSWORD: wordpress
volumes:
  wp_pusher_db_data: